.TH YAIB 1 "January, 2011" "Yet Another IRC Bot" "Yet Another IRC Bot"
.SH NAME
YAIB \- Yet Another IRC Bot
.SH SYNOPSIS
.B yaib
.SH DESCRIPTION
IRC bot easily extensible with plugins.
.SH FILES
.TP
.B ~/.yaib
Directory containing all of the configuration files.
.SH AUTHORS
YAIB was written by:
.IP
Bartosz Zasieczny
.B <barteqx@gmail.com>
.IP
Maciej Boniecki
.B <m.boniecki@gmail.com>
.IP
Silas Lenz
.B <silas.lenz@gmail.com>
